spring.application.name=system-usterek
# dodanie połączenia do bazy danych
spring.datasource.url=jdbc:mysql://localhost:3306/infrastruktura?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8
# ustawienia do logowania (lokalne)
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true